name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g truffle ganache-cli
        npm install

    - name: Compile contracts
      run: truffle compile

    - name: Start Ganache
      run: ganache-cli -d &
      continue-on-error: true

    - name: Deploy contracts
      run: truffle migrate

    - name: Run tests
      run: truffle test

    - name: Run Mythril
      run: myth analyze contracts/SimpleStorage.sol

    - name: Run Slither
      run: slither .
